sudo: false
dist: bionic

language: cpp

matrix:
  include:
    - os: linux
      compiler: clang

addons:
  apt:
    packages:
      - gperf
      - php

script:
  - mkdir build
  - cd build
  - cmake --build . --target prepare_cross_compiling
  - cd ..
  - php SplitSource.php
  - cd build
  - cmake .. && make -j${JOBS} VERBOSE=1
  - ./test/run_all_tests --filter -client
