sudo: false
dist: bionic

language: cpp

matrix:
  include:
    - os: linux
      compiler: clang

addons:
  apt:
    packages:
      - gperf

script:
  - mkdir build
  - cd build
  - cmake .. && make -j${JOBS} VERBOSE=1
  - ./test/run_all_tests --filter -client
